### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by saraedum** [conda-forge/nauty-feedstock#13]
Working on https://github.com/Normaliz/Normaliz/pull/368, I ran into illegal instructions that seem to come out of our nauty build:

```
Thread 1 "lt-normaliz" received signal SIGILL, Illegal instruction.
nauty (g_arg=g_arg@entry=0x55f7260f2180, lab=lab@entry=0x55f7261065c0, ptn=0x55f726107c60, active_arg=active_arg@entry=0x0,
    orbits_arg=orbits_arg@entry=0x55f7260dc5f0,
    options=options@entry=0x7f2938b54f00 <libnormaliz::compute_automs_by_nauty_FromGensOnly<eantic::renf_elem_class>(libnormaliz::Matrix<eantic::renf_elem_class> const&, unsigned long, libnormaliz::Matrix<eantic::renf_elem_class> const&, libnormaliz::AutomParam::Quality)::options>, stats_arg=0x7ffe482b44e0,
    ws_arg=0x55f7260ef530, worksize=120, m_arg=1, n_arg=26, canong_arg=0x55f726096030) at nauty.c:272
272     nauty.c: No such file or directory.
(gdb) where
#0  nauty (g_arg=g_arg@entry=0x55f7260f2180, lab=lab@entry=0x55f7261065c0, ptn=0x55f726107c60, active_arg=active_arg@entry=0x0,
    orbits_arg=orbits_arg@entry=0x55f7260dc5f0,
    options=options@entry=0x7f2938b54f00 <libnormaliz::compute_automs_by_nauty_FromGensOnly<eantic::renf_elem_class>(libnormaliz::Matrix<eantic::renf_elem_class> const&, unsigned long, libnormaliz::Matrix<eantic::renf_elem_class> const&, libnormaliz::AutomParam::Quality)::options>, stats_arg=0x7ffe482b44e0,
    ws_arg=0x55f7260ef530, worksize=120, m_arg=1, n_arg=26, canong_arg=0x55f726096030) at nauty.c:272
#1  0x00007f2938ab0dbf in densenauty (g=g@entry=0x55f7260f2180, lab=lab@entry=0x55f7261065c0, ptn=ptn@entry=0x55f726107c60,
    orbits=orbits@entry=0x55f7260dc5f0,
    options=options@entry=0x7f2938b54f00 <libnormaliz::compute_automs_by_nauty_FromGensOnly<eantic::renf_elem_class>(libnormaliz::Matrix<eantic::renf_elem_class> const&, unsigned long, libnormaliz::Matrix<eantic::renf_elem_class> const&, libnormaliz::AutomParam::Quality)::options>,
    stats=stats@entry=0x7ffe482b44e0, m=1, n=26, h=0x55f726096030) at naugraph.c:660
#2  0x00007f29389e0445 in libnormaliz::compute_automs_by_nauty_FromGensOnly<eantic::renf_elem_class> (Generators=..., nr_special_gens=0,
    SpecialLinForms=..., quality=<optimized out>)
    at /tmp/ruth/miniconda/envs/normaliz-build/x86_64-conda-linux-gnu/include/c++/9.3.0/bits/stl_vector.h:1165
#3  0x00007f293875bf4d in libnormaliz::AutomorphismGroup<eantic::renf_elem_class>::compute_inner (this=this@entry=0x7ffe482b48d0,
    desired_quality=@0x7ffe482b55dc: libnormaliz::AutomParam::euclidean, force_gens_x_linforms=force_gens_x_linforms@entry=false)
    at /tmp/ruth/miniconda/envs/normaliz-build/x86_64-conda-linux-gnu/include/c++/9.3.0/ext/new_allocator.h:89
#4  0x00007f293875cc25 in libnormaliz::AutomorphismGroup<eantic::renf_elem_class>::compute_polytopal (this=0x7ffe482b6e78,
    desired_quality=@0x7ffe482b55dc: libnormaliz::AutomParam::euclidean)
    at /tmp/ruth/miniconda/envs/normaliz-build/x86_64-conda-linux-gnu/include/c++/9.3.0/ext/new_allocator.h:89
#5  0x00007f293875c9d3 in libnormaliz::AutomorphismGroup<eantic::renf_elem_class>::compute (this=this@entry=0x7ffe482b6e78,
    desired_quality=desired_quality@entry=@0x7ffe482b55dc: libnormaliz::AutomParam::euclidean, force_gens_x_linforms=force_gens_x_linforms@entry=false)
    at ../../Normaliz/source/libnormaliz/automorph.cpp:433
#6  0x00007f293884bd38 in libnormaliz::Cone<eantic::renf_elem_class>::compute_euclidean_automorphisms (this=this@entry=0x7ffe482b59c0, ToCompute=...)
    at /tmp/ruth/miniconda/envs/normaliz-build/x86_64-conda-linux-gnu/include/c++/9.3.0/ostream:108
#7  0x00007f2938838c7b in libnormaliz::Cone<eantic::renf_elem_class>::compute (this=0x7ffe482b59c0, ToCompute=...)
    at ../../Normaliz/source/libnormaliz/integer.h:185
#8  0x000055f7252cb1b9 in compute_and_output<eantic::renf_elem_class, eantic::renf_elem_class> (options=..., input=..., num_param_input=...,
    polynomial=..., number_field_ref=..., add_input=...) at ../../Normaliz/source/libnormaliz/options.h:101
#9  0x000055f7252c37b9 in process_data (options=..., command_line=...) at ../../Normaliz/source/normaliz.cpp:403
#10 0x000055f7252c452f in main (argc=2, argv=0x7ffe482b7998) at ../../Normaliz/source/normaliz.cpp:185
```

That's the CPU:
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
stepping        : 1
microcode       : 0xb00001f
cpu MHz         : 1198.558
cache size      : 30720 KB
physical id     : 0
siblings        : 12
core id         : 0
cpu cores       : 12
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips        : 4394.56
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

**Comment by saraedum** [comment]
The line with the supposed problem does not do anything fancy. So this is more likely memory corruption.
